#!/bin/bash
# write standard output to file
##PBS -o job.out
# Provision resources (Time, memory)
#PBS -l walltime=10:00:00,nodes=1,mem=3G

# Notification settings
#PBS -M nguyen@cs.tu-darmstadt.de
# Sending email upon beginning and ending of the execution
#PBS -m be

# change to path with your executale
cd /home/darmstadt/nguyeng/sim/omnetpp/so/simulations/run-scripts/

# start your program (execution command/script)

