//
// Generated file, do not edit! Created by opp_msgc 4.2 from applications/common/messages/DpControlInfo.msg.
//

#ifndef _DPCONTROLINFO_M_H_
#define _DPCONTROLINFO_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "IPvXAddress.h"
// }}



/**
 * Class generated from <tt>applications/common/messages/DpControlInfo.msg</tt> by opp_msgc.
 * <pre>
 * class DpControlInfo
 * {
 *     IPvXAddress srcAddr;  
 *     IPvXAddress destAddr; 
 *     int srcPort;   
 *     int destPort;  
 * }
 * </pre>
 */
class DpControlInfo : public ::cObject
{
  protected:
    IPvXAddress srcAddr_var;
    IPvXAddress destAddr_var;
    int srcPort_var;
    int destPort_var;

  private:
    void copy(const DpControlInfo& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DpControlInfo&);

  public:
    DpControlInfo();
    DpControlInfo(const DpControlInfo& other);
    virtual ~DpControlInfo();
    DpControlInfo& operator=(const DpControlInfo& other);
    virtual DpControlInfo *dup() const {return new DpControlInfo(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual IPvXAddress& getSrcAddr();
    virtual const IPvXAddress& getSrcAddr() const {return const_cast<DpControlInfo*>(this)->getSrcAddr();}
    virtual void setSrcAddr(const IPvXAddress& srcAddr);
    virtual IPvXAddress& getDestAddr();
    virtual const IPvXAddress& getDestAddr() const {return const_cast<DpControlInfo*>(this)->getDestAddr();}
    virtual void setDestAddr(const IPvXAddress& destAddr);
    virtual int getSrcPort() const;
    virtual void setSrcPort(int srcPort);
    virtual int getDestPort() const;
    virtual void setDestPort(int destPort);
};

inline void doPacking(cCommBuffer *b, DpControlInfo& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DpControlInfo& obj) {obj.parsimUnpack(b);}


#endif // _DPCONTROLINFO_M_H_
