//
// Generated file, do not edit! Created by opp_msgc 4.2 from applications/common/messages/VideoChunkPacket.msg.
//

#ifndef _VIDEOCHUNKPACKET_M_H_
#define _VIDEOCHUNKPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include <PeerStreamingPacket_m.h>
// }}



/**
 * Class generated from <tt>applications/common/messages/VideoChunkPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet VideoChunkPacket extends PeerStreamingPacket
 * {
 *     packetGroup = PACKET_GROUP_VIDEO_CHUNK;
 *     long seqNumber @getter(getSeqNumber) @setter(setSeqNumber);
 *     double timeStamp @getter(getTimeStamp) @setter(setTimeStamp);
 * }
 * </pre>
 */
class VideoChunkPacket : public ::PeerStreamingPacket
{
  protected:
    long seqNumber_var;
    double timeStamp_var;

  private:
    void copy(const VideoChunkPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VideoChunkPacket&);

  public:
    VideoChunkPacket(const char *name=NULL, int kind=0);
    VideoChunkPacket(const VideoChunkPacket& other);
    virtual ~VideoChunkPacket();
    VideoChunkPacket& operator=(const VideoChunkPacket& other);
    virtual VideoChunkPacket *dup() const {return new VideoChunkPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual long getSeqNumber() const;
    virtual void setSeqNumber(long seqNumber);
    virtual double getTimeStamp() const;
    virtual void setTimeStamp(double timeStamp);
};

inline void doPacking(cCommBuffer *b, VideoChunkPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, VideoChunkPacket& obj) {obj.parsimUnpack(b);}


#endif // _VIDEOCHUNKPACKET_M_H_
